---
- name: Define slapd installation settings
  debconf:
    name: "slapd"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - question: 'slapd/internal/adminpw'
      value: '{{ openldap_admin_password }}'
      vtype: 'password'
    - question: 'slapd/password1'
      value: '{{ openldap_admin_password }}'
      vtype: 'password'
    - question: 'slapd/password2'
      value: '{{ openldap_admin_password }}'
      vtype: 'password'
    - question: 'slapd/internal/generated_adminpw'
      value: '{{ openldap_admin_password }}'
      vtype: 'password'
    - question: 'slapd/no_configuration'
      value: 'false'
      vtype: 'boolean'
    - question: "slapd/purge_database"
      value: 'true'
      vtype: 'boolean'
    - question: "slapd/backend"
      value: 'MDB'
      vtype: 'string'
    - question: "slapd/move_old_database"
      value: 'true'
      vtype: 'boolean'
    - question: "slapd/domain"
      value: "{{ pri_domain_name }}"
      vtype: 'string'
    - question: "shared/organization"
      value: "{{ openldap_org }}"
      vtype: 'string'

- name: Install required packages
  apt:
    name: "{{ openldap_debian_packages }}"
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Move Backup Files to another folder
  command: mv {{ item }} {{ item }}.{{ ansible_date_time.epoch }}
  loop:
    - "/var/backups/unknown-2.4.47+dfsg-3+deb10u6.ldapdb"
    - "/var/backups/slapd-2.4.47+dfsg-3+deb10u6"

- name: Reconfigure slapd
  command: dpkg-reconfigure -f noninteractive slapd
  become: yes

- name: Restart slapd
  systemd:
    name: slapd
    enabled: yes
    daemon_reload: yes
    state: restarted
