# apache/handlers/main.yml
#
---

- name: reload apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: reloaded
  become: true

- name: restart apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted
  become: true
