---
# tasks file for fedreg-agent

- name: Install basic common utils
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3-venv
  become: yes
  tags:
    - agent
    - basic_common_utils
