---
# tasks file for fedreg-agent

- name: Configuration tasks
  import_tasks: "configure-common.yml"

- name: Deploy tasks
  import_tasks: "deploy.yml"

- name: Setup services
  import_tasks: "services.yml"

