---
- name: Ensure apache SSL certificate directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item.certificate_file | dirname }}"
    owner: "{{ apache_ssl_certificate_file_owner }}"
    group: "{{ apache_ssl_certificate_file_group }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ apache_vhosts_ssl }}"
  when: item.certificate_file is defined and item.certificate is defined

- name: Ensure apache SSL certificates are copied
  become: true
  ansible.builtin.copy:
    dest: "{{ item.certificate_file }}"
    content: "{{ item.certificate }}"
    owner: "{{ apache_ssl_certificate_file_owner }}"
    group: "{{ apache_ssl_certificate_file_group }}"
    mode: "{{ apache_ssl_certificate_file_mode }}"
    backup: true
  with_items:
    - "{{ apache_vhosts_ssl }}"
  when: item.certificate_file is defined and item.certificate is defined
  notify: Restart apache

- name: Ensure apache SSL certificate key directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item.certificate_key_file | dirname }}"
    owner: "{{ apache_ssl_certificate_key_file_owner }}"
    group: "{{ apache_ssl_certificate_key_file_group }}"
    state: directory
    mode: "0775"
  with_items:
    - "{{ apache_vhosts_ssl }}"
  when: item.certificate_key_file is defined and item.certificate_key is defined

- name: Ensure apache SSL certificate keys are copied
  become: true
  ansible.builtin.copy:
    dest: "{{ item.certificate_key_file }}"
    content: "{{ item.certificate_key }}"
    owner: "{{ apache_ssl_certificate_key_file_owner }}"
    group: "{{ apache_ssl_certificate_key_file_group }}"
    mode: "{{ apache_ssl_certificate_key_file_mode }}"
    backup: true
  with_items:
    - "{{ apache_vhosts_ssl }}"
  when: item.certificate_key_file is defined and item.certificate_key is defined
  no_log: true
  notify: Restart apache
