# apache/tasks/configure-RedHat.yml
#
---

- name: Ensure sites-available and sites-enabled directories exist (RedHat)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - "{{ apache_conf_path }}/sites-available"
    - "{{ apache_conf_path }}/sites-enabled/"
  become: true

- name: Append extra parameters into Apache httpd.conf (RedHat)
  ansible.builtin.blockinfile:
    path: "{{ apache_conf_path }}/conf/httpd.conf"
    block: |
      IncludeOptional sites-enabled/*.conf
      IncludeOptional conf.d/security.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: restart apache

- name: Configure Apache security settings (RedHat)
  ansible.builtin.template:
    src: security.conf.j2
    dest: "{{ apache_conf_path }}/conf.d/security.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: restart apache

- name: Add Apache vhosts configuration (RedHat)
  ansible.builtin.template:
    src: vhosts.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: reload apache
  when: apache_create_vhosts

- name: Enable Apache vhosts configuration (RedHat)
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  become: true
  notify: reload apache
  when: apache_create_vhosts

- name: Disable default welcome page (RedHat)
  ansible.builtin.file:
    path: "{{ apache_conf_path }}/conf.d/welcome.conf"
    state: absent
  become: true
  when: apache_remove_default_page
  notify: reload apache
