# file: apache/tasks/configure-ssl-cert.yml
#
---

- name: Ensure apache SSL certificate directories exist
  ansible.builtin.file:
    path: "{{ item.certificate_file | dirname }}"
    owner: "{{ apache_ssl_certificate_file_owner }}"
    group: "{{ apache_ssl_certificate_file_group }}"
    state: directory
  loop: "{{ apache_vhosts_ssl }}"
  when:
    - item.certificate_file is defined
    - item.certificate is defined
  become: true

- name: Ensure apache SSL certificates are copied
  ansible.builtin.copy:
    dest: "{{ item.certificate_file }}"
    content: "{{ item.certificate }}"
    owner: "{{ apache_ssl_certificate_file_owner }}"
    group: "{{ apache_ssl_certificate_file_group }}"
    mode: "{{ apache_ssl_certificate_file_mode }}"
    backup: true
  loop: "{{ apache_vhosts_ssl }}"
  when:
    - item.certificate_file is defined
    - item.certificate is defined
  become: true
  no_log: true
  notify:
    - reload apache

- name: Ensure apache SSL certificate key directories exist
  ansible.builtin.file:
    path: "{{ item.certificate_key_file | dirname }}"
    owner: "{{ apache_ssl_certificate_key_file_owner }}"
    group: "{{ apache_ssl_certificate_key_file_group }}"
    state: directory
  loop: "{{ apache_vhosts_ssl }}"
  when:
    - item.certificate_key_file is defined
    - item.certificate_key is defined
  become: true

- name: Ensure apache SSL certificate keys are copied
  copy:
    dest: "{{ item.certificate_key_file }}"
    content: '{{ item.certificate_key }}'
    owner: "{{ apache_ssl_certificate_key_file_owner }}"
    group: "{{ apache_ssl_certificate_key_file_group }}"
    mode: "{{ apache_ssl_certificate_key_file_mode }}"
    backup: true
  loop: "{{ apache_vhosts_ssl }}"
  when:
    - item.certificate_key_file is defined
    - item.certificate_key is defined
  become: true
  no_log: true
  notify:
    - reload apache
