# file: apache/tasks/main.yml
#
---

- name: Fail on unsupported OS family
  ansible.builtin.fail:
    msg: >-
      This role supports only Debian and RedHat OS families
      (found {{ ansible_os_family }}).
  when: ansible_os_family not in ['Debian', 'RedHat']

- name: "Load {{ ansible_os_family }}-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install required packages
  ansible.builtin.import_tasks: install.yml

- name: Configure service
  ansible.builtin.import_tasks: configure.yml

- name: "Ensure {{ apache_service }} service is {{ apache_state }} and enabled on boot"
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
  become: true
