---
- hosts: federation-registry
  become: yes
  roles:
    - {role: federation-registry, task: configure-environment}
    - {role: federation-registry, task: postgres,tags: ['never','postgres']}
    - {role: federation-registry, task: configure-ams}
    - {role: federation-registry, task: deploy}
    - {role: federation-registry, task: deploy-documentation,tags: ['never','documentation']}
