---

- name: Ensure Shibboleth SP Apache module is installed (Debian)
  apt:
    name: "{{ shibboleth_sp_apache_mod }}"
    state: present
    update_cache: yes
    install_recommends: no
  become: yes
