# file: nginx/defaults/main.yml
#
---

# Whether to create the Virtual Host configuration
nginx_create_vhosts: false
# Name of the file that should contain the Virtual Host configuration
nginx_vhosts_filename: "vhosts.conf"
# Whether to disable the default Virtual Host configuration
nginx_remove_default_vhost: false

# SSL protocols that should be enabled
nginx_ssl_protocols: "TLSv1.3 TLSv1.2"
# SSL ciphers that should be enabled
nginx_ssl_ciphers: "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS"

# Name servers used to resolve names of upstream servers into addresses
nginx_resolver: "8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844]"

# Name of the user that should own the file containing the SSL certificate
nginx_ssl_certificate_file_owner: "root"
# Name of the group that should own the file containing the SSL certificate
nginx_ssl_certificate_file_group: "root"
# Permissions of the file containing the SSL certificate
nginx_ssl_certificate_file_mode: "0644"

# Name of the user that should own the file containing the SSL certificate key
nginx_ssl_certificate_key_file_owner: "root"
# Name of the group that should own the file containing the SSL certificate key
nginx_ssl_certificate_key_file_group: "root"
# Permissions of the file containing the SSL certificate key
nginx_ssl_certificate_key_file_mode: "0600"

# Uncomment to generate file with custom DH parameters for DHE ciphers
#nginx_dhparam_file: "dhparam.pem"
# Number of bits used for generating DH parameter set
nginx_dhparam_size: 2048

nginx_enable_rsyslog_pgsql_logs: false

#nginx_upstream_groups: 
#  - name: "web_backend"
#    servers:
#      - address: "192.168.0.1"
#        weight: 1
#      - address: "192.168.0.2"
#        weight: 1

# Uncomment to define additional directives
#nginx_extra_config: |
#  map $http_host $name {
#      hostnames;
#
#      default       0;
#
#      example.com   1;
#      *.example.com 1;
#      example.org   2;
#      *.example.org 2;
#      .example.net  3;
#      wap.*         4;
#  }
#
#  map $http_user_agent $mobile {
#      default       0;
#      "~Opera Mini" 1;
#  }

#nginx_vhosts:
#  - server_name: "www.example.org"
#    listen:
#      - "443 ssl default_server"
#      - "[::]:443 ssl default_server"
#    certificate_file: "/etc/ssl/www.example.org/fullchain.pem"
#    # Uncomment to set the content of the SSL certficate file
#    certificate: |
#      -----BEGIN CERTIFICATE-----
#      ...
#      -----END CERTIFICATE-----
#    certificate_key_file: "/etc/ssl/www.example.org/privkey.pem"
#    # Uncomment to set the content of the SSL certificate key
#    certificate_key: |
#      -----BEGIN PRIVATE KEY-----
#      ...
#      -----END PRIVATE KEY-----
#    root: "/var/www/html"
#    extra_parameters: |
#      location / {
#          # First attempt to serve request as file, then
#          # as directory, then fall back to displaying a 404.
#          try_files $uri $uri/ =404;
#      }
#
#      location /proxy {
#          proxy_pass     http://web_backend/proxy;
#          proxy_set_header Host $host;
#          proxy_set_header X-Real-IP $remote_addr;
#          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#          proxy_set_header X-Forwarded-Proto https;
#      }
