# file: tasks/install-common.yml
---

- name: Ensure util groups exist
  group:
    name: "{{ metrics_user.group }}"
    system: yes
  become: yes

- name: Ensure metrics user exists
  user:
    name: "{{ metrics_user.name }}"
    groups: "{{ metrics_user.group }}"
    comment: "{{ metrics_user.gecos }}" 
    shell: "{{ metrics_user.shell }}"
    home: "{{ metrics_user.path }}"
    system: yes
    create_home: yes
    skeleton: "/empty"
  become: yes

- name: Upgrade pip3
  pip:
    name: pip
    state: latest
    virtualenv: "{{ metrics_path }}/.venv"
    extra_args: --upgrade
  become: yes

- name: Ensure metrics python requirements are installed in virtualenv
  pip:
    requirements: "{{ metrics_path }}/requirements.txt"
    virtualenv: "{{ metrics_path }}/.venv"
    virtualenv_command: python3 -m venv
    state: latest
  become: yes

- name: fastapi systemd setup
  template:
     owner: "www-data"
     group: "www-data"
     mode: 0644
     src: templates/fastapi/fastapi.service.j2
     dest: /etc/systemd/system/fastapi.service
  notify: fastapi.service restart
  become: yes
  tags:
    - fastapi_service
