---
- name: Remove pgsql.conf file if exists
  ansible.builtin.file:
    path: "{{ rsyslogd_path }}/pgsql.conf"
    state: absent
  become: true
  when: rsyslog_pgsql_enable_logs | default(false) | bool

- name: Ensure rsyslog for nginx logs is configured
  ansible.builtin.template:
    src: rsyslogd-nginx-{{ ansible_os_family }}.conf.j2
    dest: "{{ rsyslogd_path }}/51-nginx.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: Restart rsyslog
  when: rsyslog_pgsql_enable_logs | default(false) | bool
