# rsyslog-pgsql/tasks/main.yml
#
---

- name: Fail if OS is not Debian family
  ansible.builtin.fail:
    msg: "This role supports only Debian-family systems."
  when: ansible_os_family != 'Debian'

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Install OS-specific packages
- name: Install rsyslog packages on Debian
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

#- name: Install rsyslog packages on RedHat
#  ansible.builtin.include_tasks: install-RedHat.yml
#  when: ansible_os_family == 'RedHat'

# Apply OS-independent configuration
- name: Apply common rsyslog configuration
  ansible.builtin.include_tasks: configure-common.yml

- name: Ensure rsyslog service is started and enabled on boot
  ansible.builtin.service:
    name: "{{ rsyslog_service }}"
    state: started
    enabled: true
  become: true
