# file: tasks/blocks/authentication/configure_browser_flow_cookie.yml
#
---

- set_fact:
    keycloak_auth_cookie_matches: "{{ current_realm_browser_executions.json | json_query(query) | default([]) }}"
  vars:
    query: '[?providerId == `auth-cookie` ]'
  
- set_fact:
    keycloak_auth_cookie_id: "{{ keycloak_auth_cookie_matches[0].id }}"
  when: keycloak_auth_cookie_matches | length > 0
  
# if idp_redirector_config_id is defined, it's an update, else it is a new one
- name: "Update 'browser' authentication flow of realm {{ current_realm.name }}: Cookie requirement ({{ current_realm.authentication.browser.cookie }})"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ current_realm.name }}/authentication/flows/browser/executions"
    method: PUT
    body_format: json
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    body:
      id: "{{ keycloak_auth_cookie_id }}"
      requirement: "{{ current_realm.authentication.browser.cookie }}"
      displayName: "Cookie"
      requirementChoices:
        - "REQUIRED"
        - "ALTERNATIVE"
        - "DISABLED"
      configurable: false
      providerId: "auth-cookie"
      level: 0
      index: 0
    status_code: 202
  when: keycloak_auth_cookie_id is defined
