# nginx/handlers/main.yml
#
---

- name: reload nginx
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    state: reloaded
  become: true

- name: restart nginx
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    state: restarted
  become: true
