---
# defaults file for fedreg-agent
build_branch: devel
deployer_ssp_name: deployer_ssp_demo
deployer_mitreid_name: deployer_mitreid_demo
deployer_keycloak_name: deployer_keycloak_demo
deployers_config_name: deployers_demo.config

# Virtualenv path
fedreg_agent_venv_python: "python3"
fedreg_agent_venv_path: "/srv/fedregistryagent_{{ build_branch }}"
fedreg_agent_conf_dir: "/etc/fedregistryagent_{{ build_branch }}"

# Git
fedreg_agent_registry_requirements_url: "https://raw.githubusercontent.com/rciam/rciam-federation-registry-agent/{{ build_branch }}/requirements.txt"

# Service
fedreg_agent_services_path: /etc/systemd/system
fedreg_agent_log_conf: "{{ fedreg_agent_conf_dir }}/logger.conf"
fedreg_agent_enable_ssp: false
fedreg_agent_enable_mitreid: false
fedreg_agent_enable_keycloak: false

## Federation registry agent parameters
# fedreg_agent_ams:
#   host: "example.host.com"
#   project: "ams-project-name"
#   pub_topic: "ams-publish-topic"
#   token: "ams-token"
#   time_interval: 10

## SSP
# fedreg_agent_ssp:
#   name: "pull-sub-agent-id"
#   url: "http://localhost/proxy/module.php/cron/cron.php"
#   pull_topic: "ams-topic"
#   pull_sub: "ams-sub"
#   metadata_file: "/path/to/ssp/metadata/file.php"
#   metadata_key: "ssp-metadata-key"
#   request_timeout: 30

## MITREid
# fedreg_agent_mitreid:
#   url: "https://mitreid.host"
#   pull_topic: "ams-topic"
#   pull_sub: "ams-sub"
#   refresh_token: "token"
#   client_id: "clientId"
#   client_secret: "secret"

## Keycloak
# fedreg_agent_keycloak:
#   auth_server: "https://example.com/auth"
#   realm: "example"
#   pull_topic: "ams-topic"
#   pull_sub: "ams-sub"
#   refresh_token: "token"
#   client_id: "clientId"
#   client_secret: "secret"
#   oidc_consent: false
#   saml_consent: true
#   service_account:
#     attribute_name: "voPersonID"
#     candidate: "id"
#     scope: "example.org"
