# file: keycloak/tasks/blocks/configure_theme.yml
# Configure Keycloak Vanilla Theme extension
# - loop_var: keycloak_realm
---

- name: "Add {{ keycloak_plugins.wayf.theme.name }} theme's terms of use for the realm {{ keycloak_realm.name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/realms/{{ keycloak_realm.name }}/theme-info/terms-of-use"
    method: POST
    body_format: raw
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
      Content-Type: text/html
    body: "{{ keycloak_realm.terms }}"
    status_code: 201
  when: keycloak_realm.terms is defined

- name: "Add {{ keycloak_plugins.wayf.theme.name }} theme's configuration for the realm {{ keycloak_realm.name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/realms/{{ keycloak_realm.name }}/theme-info/theme-config"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    body: "{{ keycloak_realm.config }}"
    status_code: 201
  when: keycloak_realm.config is defined

- name: "Add resource files"
  uri:
    url: "{{ keycloak_proxy_host }}/realms/{{ keycloak_realm.name }}/theme-info/resource/{{ theme_realm_resource.filename }}"
    method: POST
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    body_format: form-multipart
    body:
      file:
        filename: "{{ theme_realm_resource.path }}"
        mime_type: application/octet-stream
    status_code: 201
  loop_control:
    loop_var: theme_realm_resource
  with_items: "{{ keycloak_realm.resources | default([]) }}"
