# file: keycloak/tasks/blocks/configure_theme.yml
# Configure Keycloak Vanilla Theme extension
# - loop_var: keycloak_realm
---

- name: "Add {{ keycloak_plugins.wayf.theme.name }} theme's terms of use for the realm {{ keycloak_realm.name }}"
  uri:
    url: "{{ keycloak_host }}/realms/{{ keycloak_realm.name }}/theme-info/terms-of-use"
    method: POST
    body_format: raw
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
      Content-Type: text/html
    body: "{{ keycloak_realm.terms }}"
    status_code: 201
  when: keycloak_realm.terms is defined

- name: "Add {{ keycloak_plugins.wayf.theme.name }} theme's configuration for the realm {{ keycloak_realm.name }}"
  uri:
    url: "{{ keycloak_host }}/realms/{{ keycloak_realm.name }}/theme-info/theme-config"
    method: POST
    body_format: json
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    body: "{{ keycloak_realm.config }}"
    status_code: 201
  when: keycloak_realm.config is defined
- name: Create temporary resource directory
  ansible.builtin.tempfile:
    state: directory
    prefix: "keycloak_theme_res_"
  register: temp_theme_dir

- name: Transfer resource files to remote node
  copy:
    src: "{{ theme_realm_resource.path }}"
    dest: "{{ temp_theme_dir.path }}/{{ theme_realm_resource.filename }}"
    mode: "0644"
  loop: "{{ keycloak_realm.resources | default([]) }}"
  loop_control:
    loop_var: theme_realm_resource

- name: Upload resource files
  block:
    - name: Add resource files via curl
      command:
        argv:
          - curl
          - -s
          - -o
          - /dev/null
          - -w
          - "%{http_code}"
          - -X
          - POST
          - "{{ keycloak_host }}/realms/{{ keycloak_realm.name }}/theme-info/resource/{{ theme_realm_resource.filename }}"
          - -H
          - "Authorization: Bearer {{ tokens.json.access_token }}"
          - -F
          # Force the form field name to be 'file'
          - "file=@{{ temp_theme_dir.path }}/{{ theme_realm_resource.filename }}"
      register: kc_upload_result
      changed_when: kc_upload_result.stdout == '201'
      failed_when: kc_upload_result.stdout not in ['200', '201']
      loop: "{{ keycloak_realm.resources | default([]) }}"
      loop_control:
        loop_var: theme_realm_resource
  always:
    - name: Cleanup temporary resource directory
      file:
        path: "{{ temp_theme_dir.path }}"
        state: absent
