- name: Remove old NodeSource repository files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/nodesource.list
    - /etc/apt/sources.list.d/nodesource.list.save

- name: Install dependencies
  apt:
    pkg:
      - curl
      - git
      - nginx
      - ca-certificates
      - gnupg
      - build-essential
    state: present
    update_cache: yes

- name: Add Node.js 22 repository
  shell: curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  args:
    warn: no

- name: Upgrade Node.js from NodeSource
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: Check Node.js version
  command: node -v
  register: node_version
  changed_when: false

- name: Check npm version
  command: npm -v
  register: npm_version
  changed_when: false

- name: Show Node.js and npm versions
  debug:
    msg:
      - "Node: {{ node_version.stdout }}"
      - "npm: {{ npm_version.stdout }}"

- name: Ensure Federation Pm2 Group Exists
  group:
    name: "{{ federation_pm2_user.group }}"
    system: yes
  become: yes

- name: Ensure Federation Pm2 User Exists
  user:
    name: "{{ federation_pm2_user.name }}"
    groups: "{{ federation_pm2_user.group }}"
    comment: "{{ federation_pm2_user.gecos }}" 
    shell: "{{ federation_pm2_user.shell }}"
    home: "{{ federation_pm2_user.home }}"
    system: yes
    create_home: yes
    skeleton: "/empty"
  become: yes
