# php/tasks/main.yml
#
---

- name: Fail on unsupported OS family
  ansible.builtin.fail:
    msg: >-
      This role supports only Debian and RedHat OS families
      (found {{ ansible_os_family }}).
  when: ansible_os_family not in ['Debian', 'RedHat']

- name: "Load {{ ansible_os_family }}-specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_release}}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Define PHP packages
  ansible.builtin.set_fact:
    php_packages: "{{ php_default_packages | list }}"
  when: php_packages is not defined

- name: Define PHP configuration scan dir
  ansible.builtin.set_fact:
    php_conf_scan_dir: "{{ php_default_conf_scan_dir }}"
  when: php_conf_scan_dir is not defined

- name: "Install PHP packages for {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Configure PHP
  ansible.builtin.include_tasks: configure.yml
