---

- name: Ensure pyff SSL certificate is copied
  copy:
    content: '{{ item.content }}'
    dest: "{{ item.dest }}"
    owner: "{{ pyff_default_user }}"
    group: "{{ pyff_default_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ pyff_ssl_cert }}"
      dest: "{{ pyff_working_directory }}/sign.crt"
      mode: "0644"
    - content: "{{ pyff_ssl_cert_key }}"
      dest: "{{ pyff_working_directory }}/sign.key"
      mode: "0600"
  become: yes
  notify: pyff.service restart
  tags:
    - certificates

- name: Ensure files are copied
  copy:
    src: "{{ item }}"
    dest: "{{ pyff_working_directory }}/{{ item }}"
    owner: "{{ pyff_default_user }}"
    group: "{{ pyff_default_group }}"
    mode: 0644
    backup: yes
  with_items:
    - debug.ini
    - warn.ini
  become: yes
  notify: pyff.service restart
  tags:
    - files:copy

- name: Deploy pipeline.yml template
  template:
     owner: "{{ pyff_default_user }}"
     group: "{{ pyff_default_group }}"
     mode: 0644
     src: "templates/{{ item }}.j2"
     dest: "{{ pyff_working_directory }}/{{ item }}"
     backup: yes
  with_items:
    - pipeline.yml
  become: yes
  notify: pyff.service restart
  tags:
    - files:templates

- name: Ensure publish directory has a symbolik link under /var/www/html
  file:
    src: "{{ pyff_working_directory }}/publish"
    dest: "/var/www/html/publish"
    force: yes
    state: link
    owner: root
    group: root
    follow: false
  become: yes
  tags:
    - metadata:publish

- name: pyff systemd setup
  template:
     owner: "{{ pyff_default_user }}"
     group: "{{ pyff_default_group }}"
     mode: 0644
     src: templates/pyff.service.j2
     dest: /etc/systemd/system/pyff.service
     backup: yes
  notify: pyff.service restart
  become: yes
  tags:
    - pyff_service
