---

- name: Acquire tokens
  include_tasks: blocks/helpers/get_tokens.yml

- name: "Get the role {{ item[1].role.name }} from client {{ item[1].clientId }} and realm {{ item[0].name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item[0].name }}/clients/{{ item[1].clientId }}/roles/{{ item[1].role.name }}"
    method: "GET"
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    status_code: [200, 404]
  register: realm_role_inquiry

- set_fact:
    current_role_exists: "{% if realm_role_inquiry.status == 200 %}true{% else %}false{% endif %}"

- name: "{% if current_role_exists %}Update{% else %}Update{% endif %} the role {{ item[1].role.name }} in client {{ item[1].clientId }} and realm {{ item[0].name }}"
  uri:
    url: "{{ keycloak_proxy_host }}/admin/realms/{{ item[0].name }}/clients/{{ item[1].clientId }}/roles{% if current_role_exists %}/{{ item[1].role.name }}{% endif %}"
    method: "{% if current_role_exists %}PUT{% else %}POST{% endif %}"
    body_format: json
    headers:
      Authorization: "Bearer {{ tokens.json.access_token }}"
    body:
      "{{ item[1].role }}"
    status_code: "{% if current_role_exists %}204{% else %}201{% endif %}"